### ISSUE TITLE
cookies is not exist

### ISSUE THREAD

**Issue by zlyyy12** [aiwaves-cn/RecurrentGPT#27]
Since I did not see the requirement document you provided, I have used the latest version of the relevant libraries.
In line 48 of gradio_Server. py:
    cookie = request.headers['cookie']
I didn't see the cookie key value pair in the headers when debugging，If you know why, I hope you can provide me with a solution.
Here is my error message:：
Traceback (most recent call last):
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\gradio\blocks.py", line 1897, in process_api
    result = await self.call_function(
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\gradio\blocks.py", line 1483, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\gradio\utils.py", line 816, in wrapper
    response = f(*args, **kwargs)
  File "D:\nlp\RecurrentGPT-zh-main\gradio_server.py", line 58, in init
    cookie = request.headers['cookie']
  File "C:\Users\205\anaconda3\envs\re\lib\site-packages\starlette\datastructures.py", line 565, in __getitem__
    raise KeyError(key)
KeyError: 'cookie'

**Comment by Docerstag** [comment]
me too
